using VVardenfell.Core.Cache;

namespace VVardenfell.Runtime.Content
{
    static class RuntimeMagicEffectNameResolver
    {
        static readonly (string Gmst, string Fallback)[] s_Names =
        {
            ("sEffectWaterBreathing", "Water Breathing"),
            ("sEffectSwiftSwim", "Swift Swim"),
            ("sEffectWaterWalking", "Water Walking"),
            ("sEffectShield", "Shield"),
            ("sEffectFireShield", "Fire Shield"),
            ("sEffectLightningShield", "Lightning Shield"),
            ("sEffectFrostShield", "Frost Shield"),
            ("sEffectBurden", "Burden"),
            ("sEffectFeather", "Feather"),
            ("sEffectJump", "Jump"),
            ("sEffectLevitate", "Levitate"),
            ("sEffectSlowFall", "SlowFall"),
            ("sEffectLock", "Lock"),
            ("sEffectOpen", "Open"),
            ("sEffectFireDamage", "Fire Damage"),
            ("sEffectShockDamage", "Shock Damage"),
            ("sEffectFrostDamage", "Frost Damage"),
            ("sEffectDrainAttribute", "Drain Attribute"),
            ("sEffectDrainHealth", "Drain Health"),
            ("sEffectDrainSpellpoints", "Drain Magicka"),
            ("sEffectDrainFatigue", "Drain Fatigue"),
            ("sEffectDrainSkill", "Drain Skill"),
            ("sEffectDamageAttribute", "Damage Attribute"),
            ("sEffectDamageHealth", "Damage Health"),
            ("sEffectDamageMagicka", "Damage Magicka"),
            ("sEffectDamageFatigue", "Damage Fatigue"),
            ("sEffectDamageSkill", "Damage Skill"),
            ("sEffectPoison", "Poison"),
            ("sEffectWeaknessToFire", "Weakness to Fire"),
            ("sEffectWeaknessToFrost", "Weakness to Frost"),
            ("sEffectWeaknessToShock", "Weakness to Shock"),
            ("sEffectWeaknessToMagicka", "Weakness to Magicka"),
            ("sEffectWeaknessToCommonDisease", "Weakness to Common Disease"),
            ("sEffectWeaknessToBlightDisease", "Weakness to Blight Disease"),
            ("sEffectWeaknessToCorprusDisease", "Weakness to Corprus Disease"),
            ("sEffectWeaknessToPoison", "Weakness to Poison"),
            ("sEffectWeaknessToNormalWeapons", "Weakness to Normal Weapons"),
            ("sEffectDisintegrateWeapon", "Disintegrate Weapon"),
            ("sEffectDisintegrateArmor", "Disintegrate Armor"),
            ("sEffectInvisibility", "Invisibility"),
            ("sEffectChameleon", "Chameleon"),
            ("sEffectLight", "Light"),
            ("sEffectSanctuary", "Sanctuary"),
            ("sEffectNightEye", "Night Eye"),
            ("sEffectCharm", "Charm"),
            ("sEffectParalyze", "Paralyze"),
            ("sEffectSilence", "Silence"),
            ("sEffectBlind", "Blind"),
            ("sEffectSound", "Sound"),
            ("sEffectCalmHumanoid", "Calm Humanoid"),
            ("sEffectCalmCreature", "Calm Creature"),
            ("sEffectFrenzyHumanoid", "Frenzy Humanoid"),
            ("sEffectFrenzyCreature", "Frenzy Creature"),
            ("sEffectDemoralizeHumanoid", "Demoralize Humanoid"),
            ("sEffectDemoralizeCreature", "Demoralize Creature"),
            ("sEffectRallyHumanoid", "Rally Humanoid"),
            ("sEffectRallyCreature", "Rally Creature"),
            ("sEffectDispel", "Dispel"),
            ("sEffectSoultrap", "Soultrap"),
            ("sEffectTelekinesis", "Telekinesis"),
            ("sEffectMark", "Mark"),
            ("sEffectRecall", "Recall"),
            ("sEffectDivineIntervention", "Divine Intervention"),
            ("sEffectAlmsiviIntervention", "Almsivi Intervention"),
            ("sEffectDetectAnimal", "Detect Animal"),
            ("sEffectDetectEnchantment", "Detect Enchantment"),
            ("sEffectDetectKey", "Detect Key"),
            ("sEffectSpellAbsorption", "Spell Absorption"),
            ("sEffectReflect", "Reflect"),
            ("sEffectCureCommonDisease", "Cure Common Disease"),
            ("sEffectCureBlightDisease", "Cure Blight Disease"),
            ("sEffectCureCorprusDisease", "Cure Corprus Disease"),
            ("sEffectCurePoison", "Cure Poison"),
            ("sEffectCureParalyzation", "Cure Paralyzation"),
            ("sEffectRestoreAttribute", "Restore Attribute"),
            ("sEffectRestoreHealth", "Restore Health"),
            ("sEffectRestoreSpellPoints", "Restore Magicka"),
            ("sEffectRestoreFatigue", "Restore Fatigue"),
            ("sEffectRestoreSkill", "Restore Skill"),
            ("sEffectFortifyAttribute", "Fortify Attribute"),
            ("sEffectFortifyHealth", "Fortify Health"),
            ("sEffectFortifySpellpoints", "Fortify Magicka"),
            ("sEffectFortifyFatigue", "Fortify Fatigue"),
            ("sEffectFortifySkill", "Fortify Skill"),
            ("sEffectFortifyMagickaMultiplier", "Fortify Maximum Magicka"),
            ("sEffectAbsorbAttribute", "Absorb Attribute"),
            ("sEffectAbsorbHealth", "Absorb Health"),
            ("sEffectAbsorbSpellPoints", "Absorb Magicka"),
            ("sEffectAbsorbFatigue", "Absorb Fatigue"),
            ("sEffectAbsorbSkill", "Absorb Skill"),
            ("sEffectResistFire", "Resist Fire"),
            ("sEffectResistFrost", "Resist Frost"),
            ("sEffectResistShock", "Resist Shock"),
            ("sEffectResistMagicka", "Resist Magicka"),
            ("sEffectResistCommonDisease", "Resist Common Disease"),
            ("sEffectResistBlightDisease", "Resist Blight Disease"),
            ("sEffectResistCorprusDisease", "Resist Corprus Disease"),
            ("sEffectResistPoison", "Resist Poison"),
            ("sEffectResistNormalWeapons", "Resist Normal Weapons"),
            ("sEffectResistParalysis", "Resist Paralysis"),
            ("sEffectRemoveCurse", "Remove Curse"),
            ("sEffectTurnUndead", "Turn Undead"),
            ("sEffectSummonScamp", "Summon Scamp"),
            ("sEffectSummonClannfear", "Summon Clannfear"),
            ("sEffectSummonDaedroth", "Summon Daedroth"),
            ("sEffectSummonDremora", "Summon Dremora"),
            ("sEffectSummonAncestralGhost", "Summon Ancestral Ghost"),
            ("sEffectSummonSkeletalMinion", "Summon Skeletal Minion"),
            ("sEffectSummonLeastBonewalker", "Summon Bonewalker"),
            ("sEffectSummonGreaterBonewalker", "Summon Greater Bonewalker"),
            ("sEffectSummonBonelord", "Summon Bonelord"),
            ("sEffectSummonWingedTwilight", "Summon Winged Twilight"),
            ("sEffectSummonHunger", "Summon Hunger"),
            ("sEffectSummonGoldensaint", "Summon Golden Saint"),
            ("sEffectSummonFlameAtronach", "Summon Flame Atronach"),
            ("sEffectSummonFrostAtronach", "Summon Frost Atronach"),
            ("sEffectSummonStormAtronach", "Summon Storm Atronach"),
            ("sEffectFortifyAttackBonus", "Fortify Attack"),
            ("sEffectCommandCreatures", "Command Creature"),
            ("sEffectCommandHumanoids", "Command Humanoid"),
            ("sEffectBoundDagger", "Bound Dagger"),
            ("sEffectBoundLongsword", "Bound Longsword"),
            ("sEffectBoundMace", "Bound Mace"),
            ("sEffectBoundBattleAxe", "Bound Battle Axe"),
            ("sEffectBoundSpear", "Bound Spear"),
            ("sEffectBoundLongbow", "Bound Longbow"),
            ("sEffectExtraSpell", "EXTRA SPELL"),
            ("sEffectBoundCuirass", "Bound Cuirass"),
            ("sEffectBoundHelm", "Bound Helm"),
            ("sEffectBoundBoots", "Bound Boots"),
            ("sEffectBoundShield", "Bound Shield"),
            ("sEffectBoundGloves", "Bound Gloves"),
            ("sEffectCorpus", "Corprus"),
            ("sEffectVampirism", "Vampirism"),
            ("sEffectSummonCenturionSphere", "Summon Centurion Sphere"),
            ("sEffectSunDamage", "Sun Damage"),
            ("sEffectStuntedMagicka", "Stunted Magicka"),
            ("sEffectSummonFabricant", "Summon Fabricant"),
            ("sEffectSummonCreature01", "Call Wolf"),
            ("sEffectSummonCreature02", "Call Bear"),
            ("sEffectSummonCreature03", "Summon Bonewolf"),
            ("sEffectSummonCreature04", "sEffectSummonCreature04"),
            ("sEffectSummonCreature05", "sEffectSummonCreature05"),
        };

        public static string Resolve(ref RuntimeContentBlob blob, short effectId)
        {
            if ((uint)effectId < (uint)s_Names.Length)
            {
                var name = s_Names[effectId];
                if (!string.IsNullOrWhiteSpace(name.Gmst))
                    return RuntimeContentBlobUtility.RequireGameSettingStringByIdHash(ref blob, RuntimeContentStableHash.HashId(name.Gmst)).Trim();

                if (!string.IsNullOrWhiteSpace(name.Fallback))
                    return name.Fallback;
            }

            return $"Effect {effectId}";
        }
    }
}
